nextstore_api_parcel_payment_method_select:
    path: /api/v2/shop/parcel/{id}/payments/{paymentId}
    methods: ["PATCH"]
    defaults:
        _controller: nextstore_sylius_parcel.controller.api_parcel::selectPaymentMethod
