sylius_resource:
  resources:
    nextstore_sylius_parcel.parcel_payment:
      driver: doctrine/orm
      classes:
        model: Nextstore\SyliusParcelPlugin\Entity\Payment\ParcelPayment
        interface: Nextstore\SyliusParcelPlugin\Entity\Payment\ParcelPaymentInterface
        controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
        factory: Sylius\Component\Resource\Factory\Factory
