winzou_state_machine:
  sylius_order_item:
    class: "%sylius.model.order_item.class%"
    property_path: state
    graph: sylius_order_item
    state_machine_class: "%sylius.state_machine.class%"
    states:
      new: ~
      confirmed: ~
      cancelled: ~
      purchased: ~
      foreign_delivery_completed: ~
    transitions:
      confirm:
        from: [new]
        to: confirmed
      purchase:
        from: [confirmed]
        to: purchased
      cancel:
        from: [new]
        to: cancelled
      foreign_delivery:
        from: [purchased]
        to: foreign_delivery_completed
      restore:
        from: [cancelled]
        to: new
  nextstore_parcel:
    class: "%nextstore_sylius_parcel.model.parcel.class%"
    property_path: state
    graph: nextstore_parcel
    state_machine_class: "%sylius.state_machine.class%"
    states:
      new: ~
      confirmed: ~
      shipped_to_homeland: ~
      arrived_in_homeland: ~
      shipped_to_customer: ~
      delivered: ~
    transitions:
      confirm:
        from: [new]
        to: confirmed
      ship_to_homeland:
        from: [confirmed]
        to: shipped_to_homeland
      arrived_in_homeland:
        from: [shipped_to_homeland]
        to: arrived_in_homeland
      ship_to_customer:
        from: [arrived_in_homeland]
        to: shipped_to_customer
      deliver:
        from: [shipped_to_customer]
        to: delivered
    callbacks:
      before:
        nextstore_create_parcel_payment:
          on: ["confirm"]
          do: ["@nextstore_sylius_parcel.service.parcel", "createParcelPayment"]
          args: ["object"]

  nextstore_parcel_payment:
    class: "%nextstore_sylius_parcel.model.parcel_payment.class%"
    property_path: state
    graph: sylius_payment
    state_machine_class: "%sylius.state_machine.class%"
    states:
      cart: ~
      new: ~
      processing: ~
      authorized: ~
      partially_paid: ~
      completed: ~
      failed: ~
      cancelled: ~
      refunded: ~
    transitions:
      create:
        from: [cart]
        to: new
      process:
        from: [new]
        to: processing
      authorize:
        from: [new, processing]
        to: authorized
      partially_pay:
        from: [new, processing, authorized]
        to: partially_paid
      complete:
        from: [new, processing, authorized, partially_paid]
        to: completed
      fail:
        from: [new, processing]
        to: failed
      cancel:
        from: [new, processing, authorized]
        to: cancelled
      refund:
        from: [completed]
        to: refunded
